In [1]:
import torch

In [3]:
x = torch.arange(12, dtype=torch.float32)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [4]:
x.shape

torch.Size([12])

In [6]:
x.numel()

12

In [8]:
x.numel??

Docstring:
numel() -> int

See :func:`torch.numel`
Type:      builtin_function_or_method


In [9]:
## creating a new view
x1 = x.reshape((3,4))
x1, x1.shape

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 torch.Size([3, 4]))

In [10]:
id(x) == id(x1)

False

In [11]:
id(x), id(x1)

(140553819886752, 140553819889152)

In [12]:
x2 = x.reshape((-1, 4))
x2

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [13]:
x3 = x.reshape((3, -1))
x3

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [15]:
x4 = torch.zeros((2,3,4))
x4.shape, x4

(torch.Size([2, 3, 4]),
 tensor([[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],
 
         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]]))

In [16]:
x5 = torch.ones((2,3,4))
x5.shape, x5

(torch.Size([2, 3, 4]),
 tensor([[[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],
 
         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]]]))

In [17]:
## randomly sample from a Gaussain (Normal) distribution with mean=0 & std=1
x6 = torch.randn((3,4))
x6.shape, x6

(torch.Size([3, 4]),
 tensor([[-0.7626,  0.3591, -0.2576, -0.1043],
         [-0.4358, -0.2864,  0.4195,  0.1577],
         [-0.0144,  1.4496, -1.2019,  0.4104]]))

In [18]:
## creating a tensor with exact specified values using Python List
x7 = torch.tensor([[2,1,4,3], [1,2,3,4], [4,3,2,1]])
x7.shape, x7

(torch.Size([3, 4]),
 tensor([[2, 1, 4, 3],
         [1, 2, 3, 4],
         [4, 3, 2, 1]]))

In [19]:
[1,2]*2

[1, 2, 1, 2]

## Operations
The common standard ops like (`+, -, *, /, //, **`) have all been lifted to be ELEMENTWISE ops

In [24]:
x = torch.tensor([1.0, 2,4,8])
y = torch.tensor([2,2,2,2])


In [25]:
x+y

tensor([ 3.,  4.,  6., 10.])

In [27]:
x-y

tensor([-1.,  0.,  2.,  6.])

In [28]:
x**y

tensor([ 1.,  4., 16., 64.])

In [29]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [31]:
x = torch.arange(12, dtype=torch.float32).reshape((3,4))
y = torch.tensor([[2.0, 1, 4, 3], [1,2,3,4], [4,3,2,1]])

In [34]:
z1 = torch.cat((x,y), dim=0)
z1.shape, z1

(torch.Size([6, 4]),
 tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]))

In [35]:
z2 = torch.cat((x,y), dim=1)
z2.shape, z2

(torch.Size([3, 8]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [36]:
x.shape, y.shape

(torch.Size([3, 4]), torch.Size([3, 4]))

In [37]:
x == y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [38]:
x.sum()

tensor(66.)

In [39]:
y.sum()

tensor(30.)

In [40]:
## Broadcasting

In [42]:
a = torch.arange(3).reshape((-1,1))
b = torch.arange(2).reshape((1,-1))

In [43]:
a

tensor([[0],
        [1],
        [2]])

In [44]:
b

tensor([[0, 1]])

In [45]:
a.shape, b.shape

(torch.Size([3, 1]), torch.Size([1, 2]))

In [46]:
a+b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [47]:
a-b

tensor([[ 0, -1],
        [ 1,  0],
        [ 2,  1]])

In [48]:
a*b

tensor([[0, 0],
        [0, 1],
        [0, 2]])

In [50]:
## Slicing

x[-1], x[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [51]:
x

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [52]:
x[1,2] = 90

In [53]:
x

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5., 90.,  7.],
        [ 8.,  9., 10., 11.]])

In [56]:
x[1][2] = 100

In [57]:
x

tensor([[  0.,   1.,   2.,   3.],
        [  4.,   5., 100.,   7.],
        [  8.,   9.,  10.,  11.]])

In [58]:
x[:2, :] = 777
x

tensor([[777., 777., 777., 777.],
        [777., 777., 777., 777.],
        [  8.,   9.,  10.,  11.]])

In [59]:
x


tensor([[777., 777., 777., 777.],
        [777., 777., 777., 777.],
        [  8.,   9.,  10.,  11.]])

In [62]:
id(x) == id(x[:2])      ## slicing creates a new object and alocates new memory

False

In [63]:
y = x+y

In [64]:
id(y)

140553832236192

In [65]:
y += x**2

In [66]:
id(y)

140553832236192

In [70]:
before = id(y)
before

140553831927616

In [71]:
y -= 2*x
after = id(y)

In [72]:
before, after, before==after

(140553831927616, 140553831927616, True)

In [73]:
y

tensor([[-6.0528e+05, -6.0528e+05, -6.0529e+05, -6.0529e+05],
        [-6.0528e+05, -6.0528e+05, -6.0529e+05, -6.0529e+05],
        [-8.4000e+01, -1.0200e+02, -1.2200e+02, -1.4400e+02]])

In [76]:
z = torch.zeros_like(y)
print(id(z))

140553832606432


In [77]:
z[:] = x+y
id(z)

140553832606432

In [78]:
## numpy <--> PyTorch tensors
## shares same memory address
## changing one affects another

a = x.numpy()
b = torch.from_numpy(a)
type(a), type(b)

(numpy.ndarray, torch.Tensor)

In [79]:
id(a) == id(b)

False

In [80]:
a

array([[777., 777., 777., 777.],
       [777., 777., 777., 777.],
       [  8.,   9.,  10.,  11.]], dtype=float32)

In [81]:
b

tensor([[777., 777., 777., 777.],
        [777., 777., 777., 777.],
        [  8.,   9.,  10.,  11.]])

In [82]:
id(a)

140553832602768

In [83]:
id(b)

140553832574224

In [84]:
a == b

False

In [85]:
a

array([[777., 777., 777., 777.],
       [777., 777., 777., 777.],
       [  8.,   9.,  10.,  11.]], dtype=float32)

In [86]:
b

tensor([[777., 777., 777., 777.],
        [777., 777., 777., 777.],
        [  8.,   9.,  10.,  11.]])

In [87]:
a[0,0] = 100

In [88]:
a

array([[100., 777., 777., 777.],
       [777., 777., 777., 777.],
       [  8.,   9.,  10.,  11.]], dtype=float32)

In [89]:
b

tensor([[100., 777., 777., 777.],
        [777., 777., 777., 777.],
        [  8.,   9.,  10.,  11.]])

In [90]:
a.item()

ValueError: can only convert an array of size 1 to a Python scalar

In [91]:
a = torch.tensor(2.17)

In [92]:
a

tensor(2.1700)

In [93]:
a.item()

2.1700000762939453

In [94]:
a, a.item(), float(a), int(a)

(tensor(2.1700), 2.1700000762939453, 2.1700000762939453, 2)

In [95]:
from pprint import pprint

In [97]:
print(a, a.item(), float(a), int(a))

tensor(2.1700) 2.1700000762939453 2.1700000762939453 2


In [98]:
x, y

(tensor([[100., 777., 777., 777.],
         [777., 777., 777., 777.],
         [  8.,   9.,  10.,  11.]]),
 tensor([[-6.0528e+05, -6.0528e+05, -6.0529e+05, -6.0529e+05],
         [-6.0528e+05, -6.0528e+05, -6.0529e+05, -6.0529e+05],
         [-8.4000e+01, -1.0200e+02, -1.2200e+02, -1.4400e+02]]))

In [99]:
x.shape, y.shape

(torch.Size([3, 4]), torch.Size([3, 4]))

In [100]:
x == y

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [101]:
x < y

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [102]:
x > y

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

# Reading the dataset

In [103]:
import os

os.makedirs(os.path.join("..", "data"), exist_ok=True)
data_file = os.path.join("../data", "house_tiny.csv")

## using context manager
with open(data_file, "w") as f:
    f.write("NumRows,Alley,Price\n")
    f.write("NA,Pave,127500\n")
    f.write("2,NA,10600\n")
    f.write("4,NA,178100\n")
    f.write("NA,NA,140000\n")

In [104]:
import pandas as pd
data = pd.read_csv(data_file)
pprint(data)


   NumRows Alley   Price
0      NaN  Pave  127500
1      2.0   NaN   10600
2      4.0   NaN  178100
3      NaN   NaN  140000


In [105]:
print(data)

   NumRows Alley   Price
0      NaN  Pave  127500
1      2.0   NaN   10600
2      4.0   NaN  178100
3      NaN   NaN  140000


In [106]:
## handling missing data
## imputation & deletion

inputs, outputs = data.iloc[:, 0:2], data.iloc[:, 2]

In [107]:
inputs

NumRows Alley
0      NaN  Pave
1      2.0   NaN
2      4.0   NaN
3      NaN   NaN

In [108]:
outputs

0    127500
1     10600
2    178100
3    140000
Name: Price, dtype: int64

In [109]:
## using imputation to fill NaN values with mean
inputs = inputs.fillna(inputs.mean())

/var/folders/w8/bkz_qs7s06d1ldf776qvzgx40000gn/T/ipykernel_27810/2624341866.py:2: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  inputs = inputs.fillna(inputs.mean())


In [110]:
inputs

NumRows Alley
0      3.0  Pave
1      2.0   NaN
2      4.0   NaN
3      3.0   NaN

In [111]:
inputs = pd.get_dummies(inputs, dummy_na=True)
inputs

NumRows  Alley_Pave  Alley_nan
0      3.0           1          0
1      2.0           0          1
2      4.0           0          1
3      3.0           0          1

In [112]:
outputs

0    127500
1     10600
2    178100
3    140000
Name: Price, dtype: int64

In [113]:
type(inputs), type(outputs)

(pandas.core.frame.DataFrame, pandas.core.series.Series)

In [114]:
## Pandas <--> PyTorch

import torch
x = torch.tensor(inputs.values)
y = torch.tensor(outputs.values)


In [115]:
x.shape, x

(torch.Size([4, 3]),
 tensor([[3., 1., 0.],
         [2., 0., 1.],
         [4., 0., 1.],
         [3., 0., 1.]], dtype=torch.float64))

In [116]:
y.shape, y

(torch.Size([4]), tensor([127500,  10600, 178100, 140000]))

In [117]:
x

tensor([[3., 1., 0.],
        [2., 0., 1.],
        [4., 0., 1.],
        [3., 0., 1.]], dtype=torch.float64)

In [118]:
x.T

tensor([[3., 2., 4., 3.],
        [1., 0., 0., 0.],
        [0., 1., 1., 1.]], dtype=torch.float64)

In [119]:
x.sum()

tensor(16., dtype=torch.float64)

In [120]:
x.sum(dim=0)

tensor([12.,  1.,  3.], dtype=torch.float64)

In [121]:
x

tensor([[3., 1., 0.],
        [2., 0., 1.],
        [4., 0., 1.],
        [3., 0., 1.]], dtype=torch.float64)

In [122]:
x.sum(dim=(0,1))

tensor(16., dtype=torch.float64)

In [123]:
x.numel()

12

In [124]:
x.mean()

tensor(1.3333, dtype=torch.float64)

In [125]:
x.sum() / x.numel()

tensor(1.3333, dtype=torch.float64)

In [126]:
x.sum(dim=0, keepdim=True).shape

torch.Size([1, 3])

In [127]:
x.sum(dim=0, keepdim=True)

tensor([[12.,  1.,  3.]], dtype=torch.float64)

In [128]:
x.sum(dim=0)

tensor([12.,  1.,  3.], dtype=torch.float64)

In [129]:
x.sum(dim=0).shape

torch.Size([3])

In [130]:
x.sum(dim=1, keepdim=True)

tensor([[4.],
        [3.],
        [5.],
        [4.]], dtype=torch.float64)

In [131]:
x.sum(dim=1)

tensor([4., 3., 5., 4.], dtype=torch.float64)

In [132]:
x.shape


torch.Size([4, 3])

In [133]:
x.sum(dim=0, keepdim=True)

tensor([[12.,  1.,  3.]], dtype=torch.float64)

In [134]:
x / x.sum(dim=0, keepdim=True)

tensor([[0.2500, 1.0000, 0.0000],
        [0.1667, 0.0000, 0.3333],
        [0.3333, 0.0000, 0.3333],
        [0.2500, 0.0000, 0.3333]], dtype=torch.float64)

In [135]:
x / x.sum(dim=0)

tensor([[0.2500, 1.0000, 0.0000],
        [0.1667, 0.0000, 0.3333],
        [0.3333, 0.0000, 0.3333],
        [0.2500, 0.0000, 0.3333]], dtype=torch.float64)

In [136]:
x.sum(dim=0).shape, x.shape

(torch.Size([3]), torch.Size([4, 3]))

In [137]:
x / x.sum(dim=1, keepdim=True)

tensor([[0.7500, 0.2500, 0.0000],
        [0.6667, 0.0000, 0.3333],
        [0.8000, 0.0000, 0.2000],
        [0.7500, 0.0000, 0.2500]], dtype=torch.float64)

In [138]:
x / x.sum(dim=1)

RuntimeError: The size of tensor a (3) must match the size of tensor b (4) at non-singleton dimension 1

In [139]:
x.shape, x.sum(dim=1).shape

(torch.Size([4, 3]), torch.Size([4]))

In [140]:
x

tensor([[3., 1., 0.],
        [2., 0., 1.],
        [4., 0., 1.],
        [3., 0., 1.]], dtype=torch.float64)

In [141]:
x.cumsum(dim=0)

tensor([[ 3.,  1.,  0.],
        [ 5.,  1.,  1.],
        [ 9.,  1.,  2.],
        [12.,  1.,  3.]], dtype=torch.float64)

In [142]:
x.cumsum(dim=1)

tensor([[3., 4., 4.],
        [2., 2., 3.],
        [4., 4., 5.],
        [3., 3., 4.]], dtype=torch.float64)

In [143]:
x

tensor([[3., 1., 0.],
        [2., 0., 1.],
        [4., 0., 1.],
        [3., 0., 1.]], dtype=torch.float64)

In [144]:
torch.mv??

Docstring:
mv(input, vec, *, out=None) -> Tensor

Performs a matrix-vector product of the matrix :attr:`input` and the vector
:attr:`vec`.

If :attr:`input` is a :math:`(n \times m)` tensor, :attr:`vec` is a 1-D tensor of
size :math:`m`, :attr:`out` will be 1-D of size :math:`n`.

.. note:: This function does not :ref:`broadcast <broadcasting-semantics>`.

Args:
    input (Tensor): matrix to be multiplied
    vec (Tensor): vector to be multiplied

Keyword args:
    out (Tensor, optional): the output tensor.

Example::

    >>> mat = torch.randn(2, 3)
    >>> vec = torch.randn(3)
    >>> torch.mv(mat, vec)
    tensor([ 1.0404, -0.6361])
Type:      builtin_function_or_method


In [145]:
## L2 Norm (Eucledian Distance)
u = torch.tensor([3., -4.])

torch.norm(u)

tensor(5.)

In [147]:
torch.norm(u, p="fro")

tensor(5.)

In [148]:
%matplotlib inline

import numpy as np
from matplotlib_inline import backend_inline

def f(x):
    return (3*(x**2)) - (4*x)

In [149]:
3*1**2

3

In [150]:
def numerical_lim(f, x, h):
    return (f(x+h)-f(x)) / h

In [152]:
h = 0.1
for i in range(5):
    print(numerical_lim(f, 1, h))
    h *= 0.1

2.3000000000000043
2.029999999999976
2.0029999999993104
2.000299999997956
2.0000300000155837


In [1]:
import torch

In [1]:
from ..d2l import helpers

ImportError: attempted relative import with no known parent package